"""create raw_prices and processed_metrics tables

Revision ID: 5f91fe644b5e
Revises: aa51e6f29932
Create Date: 2026-04-23 13:36:46.944053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f91fe644b5e'
down_revision: Union[str, Sequence[str], None] = 'aa51e6f29932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sym_timestamp', 'processed_metrics', ['symbol', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sym_timestamp', 'processed_metrics', type_='unique')
    # ### end Alembic commands ###
