"""create raw_prices and processed_metrics tables

Revision ID: aa51e6f29932
Revises: 
Create Date: 2026-04-22 19:09:00.111314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa51e6f29932'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('moving_avg', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_metrics_symbol'), 'processed_metrics', ['symbol'], unique=False)
    op.create_index(op.f('ix_processed_metrics_timestamp'), 'processed_metrics', ['timestamp'], unique=False)
    op.create_table('raw_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', name='uq_s_timestamp')
    )
    op.create_index(op.f('ix_raw_prices_symbol'), 'raw_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_raw_prices_timestamp'), 'raw_prices', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_prices_timestamp'), table_name='raw_prices')
    op.drop_index(op.f('ix_raw_prices_symbol'), table_name='raw_prices')
    op.drop_table('raw_prices')
    op.drop_index(op.f('ix_processed_metrics_timestamp'), table_name='processed_metrics')
    op.drop_index(op.f('ix_processed_metrics_symbol'), table_name='processed_metrics')
    op.drop_table('processed_metrics')
    # ### end Alembic commands ###
